fantasy-congress/config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :leagues
  get 'home/index'
  root 'home#index'
  
  resources :user
  resources :politicians
  resources :matches
  resources :leagues 
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fantasy-congress/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fantasy-congress/app/models/bill.rb
class Bill < ApplicationRecord
    belongs_to :politician
end

fantasy-congress/app/models/league.rb
class League < ApplicationRecord
    has_many :users
end

fantasy-congress/app/models/league_user.rb
class LeagueUser < ApplicationRecord
    belongs_to :user
    belongs_to :league
end

fantasy-congress/app/models/match.rb
class Match < ApplicationRecord
end

fantasy-congress/app/models/politician.rb
class Politician < ApplicationRecord
    has_many :bills
    has_many :votes
    has_many :user_politicians
    has_many :users, through: :user_politicians
    
    def years_in_office
        start = self.start_date.split('-')
        start_datetime = DateTime.new(start[0].to_i, start[1].to_i, start[2].to_i)
        now = Date.today
        
        days = (now - start_datetime).to_i
        years = (days/365.25).round.to_s
    end 
    
    def full_name 
        "#{self.first_name} #{self.last_name}"
    end 
end

fantasy-congress/app/models/politician_bill.rb
class PoliticianBill < ApplicationRecord
    belongs_to :politician
    belongs_to :bill
end

fantasy-congress/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  belongs_to :league
  has_many :user_politicians
  has_many :politicians, through: :user_politicians
end

fantasy-congress/app/models/user_politician.rb
class UserPolitician < ApplicationRecord
    belongs_to :user
    belongs_to :politician
end

fantasy-congress/app/models/vote.rb
class Vote < ApplicationRecord
end

fantasy-congress/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

fantasy-congress/app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @league 
    @league_members = @league.users
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.fetch(:league, {})
    end
end

fantasy-congress/app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_action :set_politician, only: [:show]

  # GET /politicians
  # GET /politicians.json
  def index
    @politicians = Politician.all
  end

  # GET /politicians/1
  # GET /politicians/1.json
  def show
    @politician 
    @bills = @politician.bills 
    @stats = @politician.votes
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politician
      @politician = Politician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politician_params
      params.fetch(:politician, {})
    end
end

fantasy-congress/app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user 
    @caucus = @user.politicians
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:league, {})
    end
end

fantasy-congress/app/helpers/application_helper.rb
module ApplicationHelper
end

fantasy-congress/app/helpers/home_helper.rb
module HomeHelper
end

fantasy-congress/app/helpers/league_helper.rb
module LeagueHelper
end

fantasy-congress/app/helpers/leagues_helper.rb
module LeaguesHelper
end

fantasy-congress/app/helpers/match_helper.rb
module MatchHelper
end

fantasy-congress/app/helpers/matches_helper.rb
module MatchesHelper
end

fantasy-congress/app/helpers/politician_helper.rb
module PoliticianHelper
end

fantasy-congress/app/helpers/politicians_helper.rb
module PoliticiansHelper
end

fantasy-congress/app/helpers/user_helper.rb
module UserHelper
end

fantasy-congress/app/helpers/votes_helper.rb
module VotesHelper
end

fantasy-congress/app/views/politicians/_form.html.erb
<%= form_for(politician) do |f| %>
  <% if politician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(politician.errors.count, "error") %> prohibited this politician from being saved:</h2>

      <ul>
      <% politician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fantasy-congress/app/views/politicians/edit.html.erb
<h1>Editing Politician</h1>

<%= render 'form', politician: @politician %>

<%= link_to 'Show', @politician %> |
<%= link_to 'Back', politicians_path %>

fantasy-congress/app/views/politicians/index.html.erb
<div class="republican">
    <div class="header-container">
        <header class="wrapper clearfix">
          <h1 class="title">
            Politicians
          </h1>
        </header>
    </div>
    
    <div class="main-container">
      <div class="main wrapper clearfix">
        <table class="stats">
          <thead>
            <tr>
              <td>Representative</td>
            </tr>
          </thead>
          <tbody>
            <% @politicians.each do |politician| %>
              <tr>
                <td>
                  <div class="image-wrapper" style="background-image:url('https://www.govtrack.us/data/photos/<%=politician.photo_id %>-200px.jpeg')"></div>
                  <h3><%= link_to politician.full_name, politician %></h3>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>
<br>
<p id="notice"><%= notice %></p>
<%= link_to 'New Politician', new_politician_path %>

fantasy-congress/app/views/politicians/new.html.erb
<h1>New Politician</h1>

<%= render 'form', politician: @politician %>

<%= link_to 'Back', politicians_path %>

fantasy-congress/app/views/politicians/show.html.erb
<div class="<%= @politician.party.downcase %>">
    <div class="header-container">
        <header class="wrapper clearfix">
            <div class="image-wrapper" style="background-image:url('https://www.govtrack.us/data/photos/<%= @politician.photo_id %>-200px.jpeg')">
                
            </div>
            <h1 class="title">
                <span class="member-name">
                    <%= @politician.first_name %> <%= @politician.last_name %>
                </span>
                <span class="in-office"><%= @politician.party %> in office for <%= @politician.years_in_office %> years</span>
            </h1>
        </header>
    </div>
    <div class="main-container">
        <div class="main wrapper clearfix">
            <table class="stats">
                <thead>
                    <tr>
                        <td>Bill</td>
                        <td>Y/N</td>
                        <td>Lean</td>
                    </tr>
                </thead>
                <tbody>
                    <% @stats.each do |vote| %>
                        <tr>
                            <td><%= vote.bill_title %></td>
                            <% if vote.vote_cast == "+" %>
                                <td>Yay!</td>
                            <% elsif vote.vote_cast == "-" %>
                                <td>Nay!</td>
                            <% else %>
                                <td>Meh.</td>
                            <% end %>
                            
                            <% if Politician.find_by(photo_id: vote.sponsor_id).party == "Republican" %>
                                <td>Right</td>
                            <% else %>
                                <td>Left</td>
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <table class="stats">
                <thead>
                    <tr>
                        <td>Bill</td>
                        <td>Current Status</td>
                        <td>Introduced Date</td>
                        <td>Is It Alive?</td>
                    </tr>
                </thead>
                <tbody>
                    <% @bills.each do |bill| %>
                        <tr>
                            <td><%= bill.bill_type_label %> <%= bill.bill_number %></td>
                            <td><%= bill.current_status %></td>
                            <td><%= bill.introduced_date %></td>
                            
                            <% if bill.is_alive %>
                                <td>Yes!</td>
                            <% else %>
                                <td>No!</td>
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div> <!-- #main -->
    </div> <!-- #main-container -->
</div>
<div class="footer-container">
    <footer class="wrapper">
        <h3>footer</h3>
    </footer>
</div>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_politician_path(@politician) %> |
<%= link_to 'Back', politicians_path %>