fantasy-congress/config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :leagues
  get 'home/index'
  root 'home#index'
  
  resources :user
  resources :politicians
  resources :matches
  resources :leagues 
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fantasy-congress/app/models/match.rb
class Match < ApplicationRecord
end

fantasy-congress/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match 
    @player_a = User.find(@match.player_a_id)
    @player_b = User.find(@match.player_b_id)
    
    @all_politicians = @player_a.politicians.zip(@player_b.politicians)
    
    @player_a.politicians.each do |rep|
      bills_introduced = rep.bills.length
      @match.player_a_points += bills_introduced * 5
    end
    @player_b.politicians.each do |rep|
      bills_introduced = rep.bills.length
      @match.player_b_points += bills_introduced * 5
    end
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.fetch(:match, {})
    end
end

fantasy-congress/app/helpers/match_helper.rb
module MatchHelper
end

fantasy-congress/app/helpers/matches_helper.rb
module MatchesHelper
end

fantasy-congress/app/views/matches/_form.html.erb
<%= form_for(match) do |f| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fantasy-congress/app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

fantasy-congress/app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

fantasy-congress/app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

fantasy-congress/app/views/matches/show.html.erb
<div class="democrat">
    <div class="header-container">
        <header class="wrapper clearfix">
          <h1 class="title" style="text-align:center;">
              <span class="member-name">head to head</span>
              <span class="in-office">Steven vs. Rudy</span>
          </h1>
        </header>
    </div>
    <table class="stats">
        <thead>
            <tr>
                <td>PresidentBlackLamboBlue Score: 15</td>
                <td>HocusPotus Score: 20</td>
            </tr>
        </thead>
        <tbody>
            <% @all_politicians.each do |reps|%>
                <tr>
                    <% reps.each do |rep|%>
                        <td>
                            <div class="image-wrapper" style="background-image:url('https://www.govtrack.us/data/photos/<%= rep.photo_id %>-200px.jpeg')"></div>
                            <h3 class="member-name">
                                <%= link_to rep.full_name, rep %>
                            </h3>
                            <span><%= rep.bills.length * 5 %> pts.</span>
                            <% if rep.twitter_id %>
                                <%= link_to "@#{rep.twitter_id}","http://twitter.com/home?status= You%20cost%20me%20my%20matchup%20on%20Caucus%20Clash!!!%20@#{rep.twitter_id}", :target => "_blank" %>
                            <% end %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

<p id="notice"><%= notice %></p>